# Generated by Django 4.2.7 on 2023-12-02 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('job_title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('exp_min', models.CharField(max_length=2)),
                ('exp_max', models.CharField(max_length=2)),
                ('position_type', models.CharField(choices=[('full_time', 'Full Time'), ('temporary', 'Temporary'), ('contract', 'Contract'), ('freelance', 'Freelance')], max_length=20)),
                ('duration', models.CharField(blank=True, max_length=20, null=True)),
                ('interview_mode', models.CharField(max_length=100)),
                ('end_client', models.CharField(max_length=100)),
                ('salary_offer', models.CharField(max_length=20)),
                ('budget_from_client', models.CharField(max_length=20)),
                ('job_description', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.client')),
            ],
        ),
    ]
