# Generated by Django 4.2.7 on 2023-12-06 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0002_alter_jobposting_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='company_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
