# Generated by Django 4.2.7 on 2023-12-02 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'admin_table',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clientname', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'client_table',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('companyname', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'company_table',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employeeid', models.BigIntegerField(unique=True)),
                ('fullname', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], max_length=20)),
                ('password', models.CharField(default='ATS', max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('contact', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'employee_table',
            },
        ),
        migrations.CreateModel(
            name='EmployeeCompanyMapping',
            fields=[
                ('mappingid', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.employee')),
            ],
            options={
                'db_table': 'employeecompanymapping_table',
            },
        ),
    ]
